services:
  wallet:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - agora_network

networks:
  agora_network:
    external: 
      name: core_protocol_agora_network
