services:
  agora-explorer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_NODES=
    volumes:
      - ./:/app
    networks:
      - agora_network

networks:
  agora_network:
    external: 
      name: core_agora_network
