services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - agora_network

networks:
  agora_network:
    external: 
      name: agora_agora_network

